// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgI_EpoQPHN-IGekm0UvlHkkeZPVeiKJ4',
    appId: '1:640314669759:web:2598dcab73897a9a84e40a',
    messagingSenderId: '640314669759',
    projectId: 'swara-auth',
    authDomain: 'swara-auth.firebaseapp.com',
    storageBucket: 'swara-auth.firebasestorage.app',
    measurementId: 'G-RG0YQ7NTZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeFCV0ISuTHnKGw6dS4Q-44Ued0kNF8Cw',
    appId: '1:640314669759:android:9ff0f3c5991614c684e40a',
    messagingSenderId: '640314669759',
    projectId: 'swara-auth',
    storageBucket: 'swara-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaz8J7K4AjcN-emjsn2G_8hZNRgvJ30m0',
    appId: '1:640314669759:ios:6a0bf1b04995d51b84e40a',
    messagingSenderId: '640314669759',
    projectId: 'swara-auth',
    storageBucket: 'swara-auth.firebasestorage.app',
    iosClientId: '640314669759-svopqe8vjhu7oacpfn5ouinriv27ftng.apps.googleusercontent.com',
    iosBundleId: 'com.example.swara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaz8J7K4AjcN-emjsn2G_8hZNRgvJ30m0',
    appId: '1:640314669759:ios:6a0bf1b04995d51b84e40a',
    messagingSenderId: '640314669759',
    projectId: 'swara-auth',
    storageBucket: 'swara-auth.firebasestorage.app',
    iosClientId: '640314669759-svopqe8vjhu7oacpfn5ouinriv27ftng.apps.googleusercontent.com',
    iosBundleId: 'com.example.swara',
  );
}
